version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: question_generator_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: happy12347
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
